const storageTypes = {
	GET_ALL_START: 'GET_ALL_START',
	GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
	GET_ALL_FAIL: 'GET_ALL_FAIL',

	GET_ONE_START: "GET_ONE_START",
	GET_ONE_SUCCESS: "GET_ONE_SUCCESS",
	GET_ONE_FAIL: "GET_ONE_FAIL",

	POST_START: "POST_START",
	POST_SUCCESS: "POST_SUCCESS",
	POST_FAIL: "POST_FAIL",

	EDIT_START: "EDIT_START",
	EDIT_SUCCESS: "EDIT_SUCCESS",
	EDIT_FAIL: "EDIT_FAIL",
};

export default storageTypes;