const productQuotationTypes = {
	GET_PRODUCT_QUOTATION: 'GET_PRODUCT_QUOTATION',
	GET_PRODUCT_QUOTATION_SUCCESS: 'GET_PRODUCT_QUOTATION_SUCCESS',
	GET_PRODUCT_QUOTATION_FAIL: 'GET_PRODUCT_QUOTATION_FAIL',

	POST_PRODUCT_QUOTATION: "POST_PRODUCT_QUOTATION",
	POST_PRODUCT_QUOTATION_SUCCESS: "POST_PRODUCT_QUOTATION_SUCCESS",
	POST_PRODUCT_QUOTATION_FAIL: "POST_PRODUCT_QUOTATION_FAIL"

};

export default productQuotationTypes;