const storageQuotationTypes = {

	GET_ALL_STORAGE_QUOTATION_START: "GET_ALL_STORAGE_QUOTATION_START",
	GET_ALL_STORAGE_QUOTATION_SUCCESS: "GET_ALL_STORAGE_QUOTATION_SUCCESS",
	GET_ALL_STORAGE_QUOTATION_FAIL: "GET_ALL_STORAGE_QUOTATION_FAIL",

	GET_ONE_STORAGE_QUOTATION_START: "GET_ONE_STORAGE_QUOTATION_START",
	GET_ONE_STORAGE_QUOTATION_SUCCESS: "GET_ONE_STORAGE_QUOTATION_SUCCESS",
	GET_ONE_STORAGE_QUOTATION_FAIL: "GET_ONE_STORAGE_QUOTATION_FAIL",

	POST_STORAGE_QUOTATION_START: "POST_STORAGE_QUOTATION_START",
	POST_STORAGE_QUOTATION_SUCCESS: "POST_STORAGE_QUOTATION_SUCCESS",
	POST_STORAGE_QUOTATION_FAIL: "POST_STORAGE_QUOTATION_FAIL",
	
};

export default storageQuotationTypes;