const authTypes = {
	START_LOADING_USER: 'START_LOADING_USER',
	SUCCESS_CURRENT_USER: 'SUCCESS_CURRENT_USER',
	FAIL_CURRENT_USER: 'FAIL_CURRENT_USER',
};

export const fogotPasswordTypes = {
	
	START_FORGOT_PASSWORD: "START_FORGOT_PASSWORD",
	SUCCESS_FORGOT_PASSWORD: "SUCCESS_FORGOT_PASSWORD",
	FAIL_FORGOT_PASSWORD: "FAIL_FORGOT_PASSWORD"
}

export default authTypes;