

export const shipping = [
    {
        _id: "62367ef38b354550af8cc774",
        trackno: "trackinfo",
        shippersfullname: "shippersfullname",
        departurecity: "departurecity",
        departurecountry: "departurecountry",
        departuredate: "departuredate",
        consignfullnames: "consignfullnames",
        collectorfullname: "collectorfullname",
        collectoraddress: "collectortel",
        collectortel: "03453452342",
        itemsname: "itemsname",
        departuretime: "23:23",
        arrivalcity: "arrivalcity",
        arrivalcountry: "arrivalcountry",
        arrivaltime: "10:23",
        arrivaldate: "arrivaldate",
        shippersemail: "shippersidno@mail.com",
        shippersidno: "shippersidno@mail.com",
        shipperstelephone: "07342342424",
        shipperscompany: "shipperscompany",
        shippersaddress: "shippersaddress",
        consigntelephone: "0234234045",
        consignemail: "consignemail@mail.com",
        consigncompany: "consigncompany",
        consignaddress: "consignaddress",
        cosignidno: "cosignidno",
        logisticstype: "logisticstype",
        itemsweight: 123423,
        itemsweightunit: "itemsweightunit",
        itemsproducttype: "itemsproducttype",
        itemspieces: 2342,
        itemsquality: "itemsquality",
        quantifiableunit: "sdfsdfsdfsdf",
        date: "March 22 2022",
        formitems: [
            {
                number:1,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes characters for this field is 3,minimum",
                _id: "62367f16asxwe0af8cc77a"
            },
            {
                number:2,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes two",
                _id: "62367wefw35t2ec8cc77a"
            },
            {
                number:3,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes three",
                _id: "62367f1623r243wgvsdfcdsaf8cc77a"
            },
        ],
        "__v": 0
    },
    {
        _id: "62367ef38gfgc774",
        trackno: "track123",
        shippersfullname: "shippersfullname One",
        departurecity: "departurecity",
        departurecountry: "departurecountry",
        departuredate: "departuredate",
        consignfullnames: "consignfullnames",
        collectorfullname: "collectorfullname",
        collectoraddress: "collectortel",
        collectortel: "03453452342",
        itemsname: "itemsname",
        departuretime: "23:23",
        arrivalcity: "arrivalcity",
        arrivalcountry: "arrivalcountry",
        arrivaltime: "10:23",
        arrivaldate: "arrivaldate",
        shippersemail: "shippersidno@mail.com",
        shippersidno: "shippersidno@mail.com",
        shipperstelephone: "07342342424",
        shipperscompany: "shipperscompany",
        shippersaddress: "shippersaddress",
        consigntelephone: "0234234045",
        consignemail: "consignemail@mail.com",
        consigncompany: "consigncompany",
        consignaddress: "consignaddress",
        cosignidno: "cosignidno",
        logisticstype: "logisticstype",
        itemsweight: 123423,
        itemsweightunit: "itemsweightunit",
        itemsproducttype: "itemsproducttype",
        itemspieces: 2342,
        itemsquality: "itemsquality",
        quantifiableunit: "sdfsdfsdfsdf",
        date: "March 20 2022",
        formitems: [
            {
                number: 1,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes one",
                _id: "62367f168b354550afsdcsdcs8cc77a",
            },
            {
                number: 2,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes two",
                _id: "62367f168b354550afdsc8cc77a",
            },
            {
                number: 3,
                timeevents: "timeevents",
                dateevents: "sdfsdf",
                currentlocation: "currentlocation",
                shippingstatus: "shippingstatus",
                notes: "notes notes three",
                _id: "62367f168b354550af8sdcscc77a",
            },
        ],
        "__v": 0
    },
        
]